### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by cody-carlson** [shaw-dev-workshop/caption-this-0403#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by cody-carlson-learning** [comment]
hello there!

**Comment by bridgesC648** [comment]
aloha

**Comment by mleopard691** [comment]
yo

**Comment by M-a-t-a** [comment]
Hey

**Comment by georgesabbag** [comment]
This is my comment

**Comment by merylnstark** [comment]
hello word

**Comment by cpanter1** [comment]
Hello!

**Comment by joeywalraven** [comment]
Testing 1, 2, 3..

**Comment by kmartin57** [comment]
Workshopt comment

**Comment by naschinski** [comment]
GitHub ho!

**Comment by ylamay2** [comment]
Hi

**Comment by georgegreynolds** [comment]
Workshop comment

**Comment by ishegatron** [comment]
Hello world

**Comment by rogdawg** [comment]
howdy!

**Comment by KevinTWelch** [comment]
Hi!
